//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockScanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.HeadlineKeywords = new HashSet<HeadlineKeyword>();
        }
    
        public string symbol { get; set; }
        public int industry_type { get; set; }
        public string name { get; set; }
        public double price { get; set; }
    
        public virtual Industry Industry { get; set; }
        public virtual ICollection<HeadlineKeyword> HeadlineKeywords { get; set; }
        public virtual Prediction Prediction { get; set; }
    }
}
