//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockScanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeadlineKeyword
    {
        public string symbol { get; set; }
        public string keyword { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
