//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockScanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Industry
    {
        public Industry()
        {
            this.Companies = new HashSet<Company>();
            this.KeywordInfluences = new HashSet<KeywordInfluence>();
        }
    
        public int industry_type { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Company> Companies { get; set; }
        public virtual ICollection<KeywordInfluence> KeywordInfluences { get; set; }
    }
}
